### ISSUE TITLE
API无法访问

### ISSUE THREAD

**Issue by GiorgioPeng** [shituweian/visualization_back_end#1]
文档中列出的API貌似都访问不了

**Comment by shituweian** [comment]
这是田宇的疫情后端，他将整个上传后更改作为visualization的后端，还正在做修改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Giorgio ***@***.***&gt;; 
发送时间: 2021年11月6日(星期六) 中午11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [shituweian/visualization_back_end] API无法访问 (Issue #1)





 
文档中列出的API貌似都访问不了
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
